In [1]:
!ls -la dataset.csv
!head dataset.csv

ls: dataset.csv: No such file or directory
head: dataset.csv: No such file or directory

EXPLORATION

In [2]:
import pandas as pd
df = pd.read_csv("raw_data/dataset.csv")

In [3]:
df

,filestem,patient_id,study_number,timehash,gender,age,laterality,projection,initial_exam,ao_classification,cast,diagnosis_uncertain,osteopenia,fracture_visible,metal,pixel_spacing,device_manufacturer
0,0001_1297860395_01_WRI-L1_M014,1,1,1297860395,M,14.1,L,1,1.0,23r-M/2.1,NaN,NaN,NaN,NaN,NaN,0.144,Siemens
1,0001_1297860435_01_WRI-L2_M014,1,1,1297860435,M,14.1,L,2,1.0,23r-M/2.1,NaN,NaN,NaN,1.0,NaN,0.144,Siemens
2,0002_0354485735_01_WRI-R1_F012,2,1,354485735,F,12.0,R,1,1.0,23r-M/2.1,NaN,1.0,NaN,NaN,NaN,0.144,Siemens
3,0002_0354485759_01_WRI-R2_F012,2,1,354485759,F,12.0,R,2,1.0,23r-M/2.1,NaN,1.0,NaN,NaN,NaN,0.144,Siemens
4,0003_0662359226_01_WRI-R1_M011,3,1,662359226,M,11.1,R,1,1.0,23-M/3.1,NaN,NaN,NaN,1.0,NaN,0.144,Siemens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20322,6091_0590289015_02_WRI-L2_F008,6091,2,590289015,F,8.7,L,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.144,Siemens
20323,6092_0295935784_01_WRI-L1_M003,6092,1,295935784,M,3.5,L,1,1.0,22-D/1.1,NaN,NaN,NaN,NaN,NaN,0.144,Siemens
20324,6092_0295935837_01_WRI-L2_M003,6092,1,295935837,M,3.5,L,2,1.0,22-D/1.1,NaN,NaN,NaN,NaN,NaN,0.144,Siemens
20325,6093_0885712402_01_WRI-L1_M008,6093,1,885712402,M,8.4,L,1,1.0,23r-M/3.1,NaN,NaN,NaN,1.0,NaN,0.144,Siemens
20326,6093_0885712456_01_WRI-L2_M008,6093,1,885712456,M,8.4,L,2,1.0,23r-M/3.1,NaN,NaN,NaN,1.0,NaN,0.144,Siemens

In [4]:
df.describe()

,patient_id,study_number,timehash,age,projection,initial_exam,cast,diagnosis_uncertain,osteopenia,fracture_visible,metal,pixel_spacing
count,20327.000000,20327.000000,2.032700e+04,20327.000000,20327.000000,10861.0,5776.0,537.0,2473.0,13550.0,708.0,20327.000000
mean,3030.858907,1.869828,7.158175e+08,10.920151,1.508388,1.0,1.0,1.0,1.0,1.0,1.0,0.143994
std,1756.941503,1.351556,2.979092e+08,3.605313,0.509012,0.0,0.0,0.0,0.0,0.0,0.0,0.000074
min,1.000000,1.000000,7.244996e+07,0.200000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,0.143000
25%,1510.000000,1.000000,4.627350e+08,8.500000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,0.144000
50%,2995.000000,1.000000,7.156266e+08,11.200000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,0.144000
75%,4561.000000,2.000000,9.641821e+08,13.600000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,0.144000
max,6093.000000,12.000000,1.325713e+09,19.000000,3.000000,1.0,1.0,1.0,1.0,1.0,1.0,0.144000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20327 entries, 0 to 20326
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   filestem             20327 non-null  object
 1   patient_id           20327 non-null  int64
 2   study_number         20327 non-null  int64
 3   timehash             20327 non-null  int64
 4   gender               20327 non-null  object
 5   age                  20327 non-null  float64
 6   laterality           20327 non-null  object
 7   projection           20327 non-null  int64
 8   initial_exam         10861 non-null  float64
 9   ao_classification    14158 non-null  object
 10  cast                 5776 non-null   float64
 11  diagnosis_uncertain  537 non-null    float64
 12  osteopenia           2473 non-null   float64
 13  fracture_visible     13550 non-null  float64
 14  metal                708 non-null    float64
 15  pixel_spacing        20327 non-null  float64
 16  device_manufacturer  20327 non-null  object
dtypes: float64(8), int64(4), object(5)
memory usage: 2.6+ MB

In [6]:
df.shape

(20327, 17)

In [7]:
df.isna().sum()

filestem                   0
patient_id                 0
study_number               0
timehash                   0
gender                     0
age                        0
laterality                 0
projection                 0
initial_exam            9466
ao_classification       6169
cast                   14551
diagnosis_uncertain    19790
osteopenia             17854
fracture_visible        6777
metal                  19619
pixel_spacing              0
device_manufacturer        0
dtype: int64

In [8]:
df["device_manufacturer"].unique()

array(['Siemens', 'Agfa'], dtype=object)

In [9]:
df["device_manufacturer"].value_counts()

device_manufacturer
Siemens    20215
Agfa         112
Name: count, dtype: int64

In [10]:
df["laterality"].value_counts()

laterality
L    11135
R     9192
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

0

In [12]:
df = df.drop_duplicates()

In [13]:
df[df['age'] < 0]

Empty DataFrame
Columns: [filestem, patient_id, study_number, timehash, gender, age, laterality, projection, initial_exam, ao_classification, cast, diagnosis_uncertain, osteopenia, fracture_visible, metal, pixel_spacing, device_manufacturer]
Index: []

In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

In [15]:
df.head()

,filestem,patient_id,study_number,timehash,gender,age,laterality,projection,initial_exam,ao_classification,cast,diagnosis_uncertain,osteopenia,fracture_visible,metal,pixel_spacing,device_manufacturer
0,0001_1297860395_01_WRI-L1_M014,1,1,1297860395,M,14.1,L,1,1.0,23r-M/2.1,NaN,NaN,NaN,NaN,NaN,0.144,Siemens
1,0001_1297860435_01_WRI-L2_M014,1,1,1297860435,M,14.1,L,2,1.0,23r-M/2.1,NaN,NaN,NaN,1.0,NaN,0.144,Siemens
2,0002_0354485735_01_WRI-R1_F012,2,1,354485735,F,12.0,R,1,1.0,23r-M/2.1,NaN,1.0,NaN,NaN,NaN,0.144,Siemens
3,0002_0354485759_01_WRI-R2_F012,2,1,354485759,F,12.0,R,2,1.0,23r-M/2.1,NaN,1.0,NaN,NaN,NaN,0.144,Siemens
4,0003_0662359226_01_WRI-R1_M011,3,1,662359226,M,11.1,R,1,1.0,23-M/3.1,NaN,NaN,NaN,1.0,NaN,0.144,Siemens

In [16]:
df["cast"].value_counts()

cast
1.0    5776
Name: count, dtype: int64

In [17]:
df["metal"].value_counts()

metal
1.0    708
Name: count, dtype: int64

In [18]:
df['osteopenia'].value_counts()

osteopenia
1.0    2473
Name: count, dtype: int64

In [19]:
df['diagnosis_uncertain'].value_counts()

diagnosis_uncertain
1.0    537
Name: count, dtype: int64

In [20]:
df['device_manufacturer'].value_counts()

device_manufacturer
Siemens    20215
Agfa         112
Name: count, dtype: int64

In [21]:
df['study_number'].value_counts()

study_number
1     11866
2      3766
3      2230
4      1295
5       672
6       291
7       106
8        55
9        24
10       10
11        8
12        4
Name: count, dtype: int64

In [22]:
df['projection'].value_counts(dropna=False)

projection
2    10148
1    10086
3       93
Name: count, dtype: int64

In [23]:
df['ao_classification'].isna().sum()

6169

CLEANING

In [24]:
df_filtered_CNN = df[df['cast'].isna() & df['metal'].isna() & df['diagnosis_uncertain'].isna() & df['osteopenia'].isna() & (df['projection']<3)]

In [25]:
df_filtered_CNN = df_filtered_CNN.drop(columns=['cast', 'metal', 'osteopenia', 'diagnosis_uncertain', 'study_number', 'device_manufacturer', 'initial_exam', 'timehash', 'ao_classification'], errors='ignore')

In [26]:
df_filtered_CNN

,filestem,patient_id,gender,age,laterality,projection,fracture_visible,pixel_spacing
0,0001_1297860395_01_WRI-L1_M014,1,M,14.1,L,1,NaN,0.144
1,0001_1297860435_01_WRI-L2_M014,1,M,14.1,L,2,1.0,0.144
4,0003_0662359226_01_WRI-R1_M011,3,M,11.1,R,1,1.0,0.144
5,0003_0662359351_01_WRI-R2_M011,3,M,11.1,R,2,1.0,0.144
10,0004_0542630449_01_WRI-L1_M003,4,M,3.2,L,1,NaN,0.144
...,...,...,...,...,...,...,...,...
20322,6091_0590289015_02_WRI-L2_F008,6091,F,8.7,L,2,NaN,0.144
20323,6092_0295935784_01_WRI-L1_M003,6092,M,3.5,L,1,NaN,0.144
20324,6092_0295935837_01_WRI-L2_M003,6092,M,3.5,L,2,NaN,0.144
20325,6093_0885712402_01_WRI-L1_M008,6093,M,8.4,L,1,1.0,0.144
20326,6093_0885712456_01_WRI-L2_M008,6093,M,8.4,L,2,1.0,0.144

In [27]:
len(df_filtered_CNN)

11312

In [28]:
df_filtered_CNN['projection'].value_counts(dropna=False)

projection
2    5708
1    5604
Name: count, dtype: int64

In [29]:
df_filtered_CNN['fracture_visible'].value_counts(dropna=False)

fracture_visible
NaN    5943
1.0    5369
Name: count, dtype: int64

PREPROCESSOR

In [30]:
import os

df_filtered_CNN['file_path'] = df_filtered_CNN['filestem'].apply(lambda x: os.path.join('images', f'{x}.png'))

In [31]:
data_model = df_filtered_CNN.copy()
data_model['fracture_visible'] = data_model['fracture_visible'].fillna(0)
data_model['file_path'] = "notebooks_modibo/cnn_images/" + data_model['filestem'] + ".png"

size_data_model = len(data_model)
data_model = data_model.sample(size_data_model, random_state=42).reset_index(drop=True)

i_train_val = round(size_data_model * 0.7)
i_test = round(size_data_model * 0.8)

data_train = data_model.iloc[:i_train_val, :]
data_val = data_model.iloc[i_train_val:i_test, :]
data_test = data_model.iloc[i_test:, :]

X_train = data_train['file_path']
y_train = data_train['fracture_visible']

X_val = data_val['file_path']
y_val = data_val['fracture_visible']

X_test = data_test['file_path']
y_test = data_test['fracture_visible']

MODEL CNN

In [32]:
df_cnn = df_filtered_CNN.copy()

# Transformer NaN en 0
# 1 = fracture visible
# 0 = pas de fracture visible
df_cnn["fracture"] = df_cnn["fracture_visible"].fillna(0).astype(int)

print("Nombre total :", len(df_cnn))
print(df_cnn["fracture"].value_counts())

Nombre total : 11312
fracture
0    5943
1    5369
Name: count, dtype: int64

In [33]:
import os
import glob
import zipfile
import shutil

TARGET_DIR = "notebooks_modibo/cnn_images"

# Supprimer l'ancien dossier
if os.path.exists(TARGET_DIR):
    shutil.rmtree(TARGET_DIR)

os.makedirs(TARGET_DIR, exist_ok=True)

# Liste des images nécessaires
wanted = set(df_cnn["filestem"].astype(str) + ".png")

zip_files = glob.glob("/content/images_part*.zip")

found = set()

for zip_path in zip_files:

    print("Lecture :", zip_path)

    with zipfile.ZipFile(zip_path, "r") as z:

        for member in z.namelist():

            filename = os.path.basename(member)

            if filename in wanted and filename not in found:

                destination = os.path.join(TARGET_DIR, filename)

                with z.open(member) as source, open(destination, "wb") as target:
                    shutil.copyfileobj(source, target)

                found.add(filename)

print("\nImages demandées :", len(wanted))
print("Images retrouvées :", len(found))
print("Images manquantes :", len(wanted - found))

Images demandées : 11312
Images retrouvées : 0
Images manquantes : 11312

In [34]:
df_cnn["image_path"] = (
    "/content/cnn_images/"
    + df_cnn["filestem"].astype(str)
    + ".png"
)

print("Lignes dataframe :", len(df_cnn))

print(
    "Images présentes :",
    df_cnn["image_path"].apply(os.path.isfile).sum()
)

print(df_cnn["fracture"].value_counts())

Lignes dataframe : 11312
Images présentes : 0
fracture
0    5943
1    5369
Name: count, dtype: int64

In [35]:
df_cnn = df_filtered_CNN.copy()

df_cnn["fracture"] = (
    df_cnn["fracture_visible"]
    .fillna(0)
    .astype(int)
)

df_cnn["file_path"] = (
    "/content/cnn_images/"
    + df_cnn["filestem"].astype(str)
    + ".png"
)

print(len(df_cnn))
print(df_cnn["fracture"].value_counts())
print(df_cnn["file_path"].apply(os.path.exists).sum())

11312
fracture
0    5943
1    5369
Name: count, dtype: int64
0

In [36]:
from sklearn.model_selection import GroupShuffleSplit

# 70 % train / 30 % temporaire
split1 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.30,
    random_state=42
)

train_idx, temp_idx = next(
    split1.split(
        df_cnn,
        y=df_cnn["fracture"],
        groups=df_cnn["patient_id"]
    )
)

train_df = df_cnn.iloc[train_idx].copy()
temp_df = df_cnn.iloc[temp_idx].copy()

# Séparer les 30 % restants en 15 % validation / 15 % test
split2 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.50,
    random_state=42
)

val_idx, test_idx = next(
    split2.split(
        temp_df,
        y=temp_df["fracture"],
        groups=temp_df["patient_id"]
    )
)

val_df = temp_df.iloc[val_idx].copy()
test_df = temp_df.iloc[test_idx].copy()

print("TRAIN :", len(train_df))
print(train_df["fracture"].value_counts())

print("\nVALIDATION :", len(val_df))
print(val_df["fracture"].value_counts())

print("\nTEST :", len(test_df))
print(test_df["fracture"].value_counts())

print("\nTOTAL :", len(train_df) + len(val_df) + len(test_df))

TRAIN : 7943
fracture
0    4195
1    3748
Name: count, dtype: int64

VALIDATION : 1691
fracture
0    855
1    836
Name: count, dtype: int64

TEST : 1678
fracture
0    893
1    785
Name: count, dtype: int64

TOTAL : 11312

In [37]:
import tensorflow as tf

IMG_SIZE = (256, 256)
BATCH_SIZE = 16

def load_image(path, label):
    image = tf.io.read_file(path)
    image = tf.image.decode_png(image, channels=1)
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

def make_dataset(df, training=False):
    ds = tf.data.Dataset.from_tensor_slices(
        (df["file_path"].values, df["fracture"].values)
    )

    if training:
        ds = ds.shuffle(len(df))

    return (ds
            .map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
            .batch(BATCH_SIZE)
            .prefetch(tf.data.AUTOTUNE))

train_ds = make_dataset(train_df, True)
val_ds = make_dataset(val_df)
test_ds = make_dataset(test_df)

2026-08-27 15:13:26.316866: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2026-08-27 15:13:26.316901: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-08-27 15:13:26.316906: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-08-27 15:13:26.316922: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-08-27 15:13:26.316931: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [38]:
from tensorflow.keras import Sequential, layers

model = Sequential([
    layers.Input(shape=(256, 256, 1)),

    layers.Conv2D(
        16,
        (3, 3),
        padding="same",
        activation="relu"
    ),
    layers.MaxPooling2D(pool_size=(2, 2)),

    layers.Conv2D(
        32,
        (2, 2),
        padding="same",
        activation="relu"
    ),
    layers.MaxPooling2D(pool_size=(2, 2)),

    layers.Flatten(),

    layers.Dense(50, activation="relu"),

    layers.Dense(1, activation="sigmoid")
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 256, 256, 16)   │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 128, 128, 16)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 131072)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 50)             │     6,553,650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,555,941 (25.01 MB)

 Trainable params: 6,555,941 (25.01 MB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [40]:
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs= 10
)

Epoch 1/10

2026-08-27 15:13:26.759749: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-08-27 15:13:26.942941: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/5732_0933265746_01_WRI-L1_F010.png; No such file or directory
2026-08-27 15:13:26.942959: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/5228_0858620622_01_WRI-R2_M008.png; No such file or directory
2026-08-27 15:13:26.942971: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/4387_0687951705_02_WRI-L2_M013.png; No such file or directory
2026-08-27 15:13:26.942974: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/4684_1034666832_01_WRI-L2_F011.png; No such file or directory
2026-08-27 15:13:26.942987: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/5486_0765274841_01_WRI-R1_M015.png; No such file or directory
2026-08-27 15:13:26.942996: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/1423_0783269550_01_WRI-L1_F008.png; No such file or directory
2026-08-27 15:13:26.943028: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/0359_0570993171_02_WRI-R2_F008.png; No such file or directory
2026-08-27 15:13:26.943046: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/0940_1043726383_02_WRI-L1_F010.png; No such file or directory
2026-08-27 15:13:26.943058: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/4344_0868690200_01_WRI-R1_M013.png; No such file or directory
2026-08-27 15:13:26.943069: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/2572_1079545423_01_WRI-R2_F011.png; No such file or directory
2026-08-27 15:13:26.943095: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/1553_1118388228_01_WRI-R1_M011.png; No such file or directory
2026-08-27 15:13:26.943102: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/3580_0396988572_01_WRI-L1_F006.png; No such file or directory
2026-08-27 15:13:26.943116: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: NOT_FOUND: /content/cnn_images/4387_0687951705_02_WRI-L2_M013.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]]
2026-08-27 15:13:26.943124: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/1477_1013501491_01_WRI-L2_F009.png; No such file or directory
2026-08-27 15:13:26.943144: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/2231_0392629975_02_WRI-R1_F009.png; No such file or directory
2026-08-27 15:13:26.943176: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/5907_0418780922_01_WRI-R1_F011.png; No such file or directory
2026-08-27 15:13:26.943182: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/3125_0956641698_02_WRI-L2_M012.png; No such file or directory
2026-08-27 15:13:26.943202: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/1590_0984643851_01_WRI-R1_M015.png; No such file or directory
2026-08-27 15:13:26.943212: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/5834_0376004744_01_WRI-R1_M008.png; No such file or directory
2026-08-27 15:13:26.943223: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/5515_0264287531_02_WRI-L2_M015.png; No such file or directory
2026-08-27 15:13:26.943235: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 2797072880713606710
2026-08-27 15:13:26.943243: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 4566473783936444310
2026-08-27 15:13:26.943244: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/3845_0591505156_02_WRI-L2_M008.png; No such file or directory
2026-08-27 15:13:26.943267: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/2087_0334046980_01_WRI-R2_M012.png; No such file or directory
2026-08-27 15:13:26.943274: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/4103_0639212144_01_WRI-L1_F010.png; No such file or directory
2026-08-27 15:13:26.943280: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/2870_1109763821_02_WRI-R1_M012.png; No such file or directory
2026-08-27 15:13:26.943289: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/0899_0624269611_01_WRI-R2_F011.png; No such file or directory
2026-08-27 15:13:26.943308: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 16074008867559349136
2026-08-27 15:13:26.943317: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 11193608507572030658
2026-08-27 15:13:26.943320: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 8897369687211822572
2026-08-27 15:13:26.943326: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 17523720122348240466
2026-08-27 15:13:26.943328: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 18196207805682880488
2026-08-27 15:13:26.943331: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/1654_0391923890_01_WRI-R1_M006.png; No such file or directory
2026-08-27 15:13:26.943344: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/6002_0323040382_01_WRI-L2_F006.png; No such file or directory
2026-08-27 15:13:26.943374: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at whole_file_read_ops.cc:116 : NOT_FOUND: /content/cnn_images/4970_0732594170_01_WRI-L1_F007.png; No such file or directory
2026-08-27 15:13:26.943404: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 9700640812036241355
2026-08-27 15:13:26.943409: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 3816413042879476123
2026-08-27 15:13:26.943411: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 4185547191945361371
2026-08-27 15:13:26.943415: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 3890910090908244883
2026-08-27 15:13:26.943417: I tensorflow/core/framework/local_rendezvous.cc:422] Local rendezvous recv item cancelled. Key hash: 4363321925650949945
2026-08-27 15:13:26.957183: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: NOT_FOUND: /content/cnn_images/4387_0687951705_02_WRI-L2_M013.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]]
	 [[StatefulPartitionedCall/adam/Add_2/_34]]

NotFoundError: Graph execution error:

Detected at node ReadFile defined at (most recent call last):
<stack traces unavailable>
Detected at node ReadFile defined at (most recent call last):
<stack traces unavailable>
2 root error(s) found.
  (0) NOT_FOUND:  /content/cnn_images/4387_0687951705_02_WRI-L2_M013.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]]
	 [[StatefulPartitionedCall/adam/Add_2/_34]]
  (1) NOT_FOUND:  /content/cnn_images/4387_0687951705_02_WRI-L2_M013.png; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_multi_step_on_iterator_1798]